## Imports

In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
import torchvision.models as m
from torch.utils.data import DataLoader
from transforms import *
from torchvision.transforms import Compose
from torchsummary import summary
from repeat_image_dataset import RepeatImageDataset
from random_caption_dataset import RandomCaptionDataset
from text_preprocessing import *

print(f'PyTorch version: {torch.__version__}')
print("GPU found :)" if torch.cuda.is_available() else "No GPU :(")

# Device configuration
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

PyTorch version: 1.7.1
GPU found :)


In [2]:
IMAGE_SIZE = 224

## Datas section

In [3]:
# Init text preprocessing class

text_preprocessor = TextPreprocessor('./flickr8k/annotations/annotations_image_id.csv', sep=';')

(array([67]),)
(array([68]),)


In [4]:
transforms = Compose([Rescale(256), 
                      RandomCrop(IMAGE_SIZE), 
                      ToTensor(), Normalize(),
                      OneHotEncode(text_preprocessor)])

train_repeat_dataset = RepeatImageDataset('./flickr8k/images/train/', transform=transforms)
train_random_dataset = RandomCaptionDataset('./flickr8k/images/train/', transform=transforms)

In [5]:
train_random_dataset[0]['caption']

['A child in a pink dress is climbing up a set of stairs in an entry way .', 'A girl going into a wooden building .', 'A little girl climbing into a wooden playhouse .', 'A little girl climbing the stairs to her playhouse .', 'A little girl in a pink dress going into a wooden cabin .']


array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [6]:
text_preprocessor.vect_to_caption(train_random_dataset[0]['caption'])

['A child in a pink dress is climbing up a set of stairs in an entry way .', 'A girl going into a wooden building .', 'A little girl climbing into a wooden playhouse .', 'A little girl climbing the stairs to her playhouse .', 'A little girl in a pink dress going into a wooden cabin .']
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[0. 0. 0. ... 0. 0. 0.]


'<start> A girl going into a wooden building . <stop>'

In [7]:
batch_size = 1

# Build data loaders
print(len(train_random_dataset))
train_repeat_loader = DataLoader(train_repeat_dataset, batch_size=batch_size)
train_random_loader = DataLoader(train_random_dataset, batch_size=batch_size)

8092


## Model section

In [8]:
# retrieve pretrained model for features extraction
resnet = m.resnet18(pretrained=True).to(device)
#resnet

In [9]:
# Keep only the feature extraction layers of the model
features = nn.Sequential(*(list(resnet.children())[:-2]), nn.Flatten())
summary(features, (3, 224, 224))

----------------------------------------------------------------
        Layer (type)               Output Shape         Param #
            Conv2d-1         [-1, 64, 112, 112]           9,408
       BatchNorm2d-2         [-1, 64, 112, 112]             128
              ReLU-3         [-1, 64, 112, 112]               0
         MaxPool2d-4           [-1, 64, 56, 56]               0
            Conv2d-5           [-1, 64, 56, 56]          36,864
       BatchNorm2d-6           [-1, 64, 56, 56]             128
              ReLU-7           [-1, 64, 56, 56]               0
            Conv2d-8           [-1, 64, 56, 56]          36,864
       BatchNorm2d-9           [-1, 64, 56, 56]             128
             ReLU-10           [-1, 64, 56, 56]               0
       BasicBlock-11           [-1, 64, 56, 56]               0
           Conv2d-12           [-1, 64, 56, 56]          36,864
      BatchNorm2d-13           [-1, 64, 56, 56]             128
             ReLU-14           [-1, 64,

## Build LSTM + Embedding

In [10]:
vocab_size = text_preprocessor.vocab_size

class LSTMCaptioning(nn.Module):
    
    def __init__(self, input_size, hidden_size):
        super(LSTMCaptioning, self).__init__()
        self.lstm = nn.LSTM(input_size, hidden_size)
        
    def forward(self, x, previous_state):
         
        # Get hidden states for each t (out) , and latest one (h = (ht, ct))
        out, ht = self.lstm(x.view(len(inputs), 1, -1), previous_state)
        
        # Compute probability distribution over all words for this t
        pt = F.softmax(ht, dim=1)
                           
        return out, ht, pt

embedding = nn.Embedding(vocab_size, 25088)

## Train model

In [14]:
input_size = 25088
hidden_size = vocab_size
learning_rate = 0.001
lstm = LSTMCaptioning(input_size, hidden_size)
optimizer = torch.optim.Adam(lstm.parameters(), lr=learning_rate)

num_epoch = 10
loss_function = nn.NLLLoss()

for epoch in range(num_epoch):
    for i, sample in enumerate(train_random_loader):
        
        image, caption = sample['image'].to(device, dtype=torch.float), sample['caption'].to(device, dtype=torch.float)
        
        # Reset grad
        lstm.zero_grad()
        
        # Get the input image embedding 
        image_embedding = features(image)
        
        # Forward pass for t=-1: image
        out, hidden, probs = lstm(image_embedding)
        
        # Forward pass for t>=0: words
        for word in caption:
            word_embedding = embedding(word)
            out, hidden, probs = lstm(word_embedding)
        
        # Compute loss and backprop
        loss = loss_function(out, targets)
        loss.backward()
        optimizer.step()
        

['A child in a pink dress is climbing up a set of stairs in an entry way .', 'A girl going into a wooden building .', 'A little girl climbing into a wooden playhouse .', 'A little girl climbing the stairs to her playhouse .', 'A little girl in a pink dress going into a wooden cabin .']


TypeError: forward() missing 1 required positional argument: 'previous_state'

In [ ]:
# Save model 
torch.save(model.state_dict(), './models/')